### ISSUE TITLE
Flush is unsafe

### ISSUE THREAD

**Issue by apechimp** [honeycombio/libhoney-go#80]
As advertised, [`Flush`](https://godoc.org/github.com/honeycombio/libhoney-go#Flush) is not threadsafe. However, this is problematic for our use case. We are using AWS lambda and are following the recommendation to call `Flush` before the function exits. We also set a timeout and respect the deadline on the context that the lambda SDK passes to our handler. The issue is that if the flush does not complete before that timeout or deadline, we'll panic on the next invocation because we'll be creating events while the flush is happening. Generally, this effect is not a big deal, but it makes our application very sensitive to issues with the honeycomb API because our application will crash when the API is responding too slowly.

It _seems_ that this lack of thread safety is not needed. There appear to be (at least) two options to make it safe.
1. Replace the [`muster.Client`](https://github.com/honeycombio/libhoney-go/blob/master/transmission/transmission.go#L75) and start the new client when `Flush` is called. This way new events can be enqueued into the new `muster.Client`, but events that were written to the old `muster.Client` will be sent.
2. Add a temporary queue that is used while a flush is happening so that new events can queue while we wait for the flush to complete.

I'd happily write a pull request for either of these approaches if they're palatable.

**Comment by maplebed** [comment]
This is an interesting quandary, thanks for raising it.

The `Flush` method essentially calls `Stop` then `Start`, and it's the time between stopped and restarted state that's the issue, right? 

What would you think of exploring the idea of saving off a copy of the existing transmission then inverting the order? Instead of `Stop` then `Start`, make it `Start` then `Stop`? 
* Copying over settings, start a new transmission
* Inside a lock, swap the newly started transmission for the old one
* Close the old one

I don't know if this is feasible - it's been too long since I dug deeply in this code. I think it might involve adding a new function to the `Sender` interface: `Copy` which would return a (started or not) copy of the transmission implementation. I don't know how I feel about adding to the `Sender` interface - if it were possible to perform the "copy" by creating a new one based on the configs that the Client still has, that would be even better. 

My thoughts on your two suggestions:
# `muster` is inside the default transmission while `Flush` is on the client. I'm not super clear on how to pull this off without violating the interface abstraction between the `client` and `transmission`.
# it feels a little dodgy to be building queues of events outside the transmission, whose whole job is enqueuing events. :/  

What do you think? I'm not sure I really understand the way your first suggestion would happen and it wouldn't surprise me that I've misunderstood. I think it would be a really nice thing to make `Flush` threadsafe - it's a real bummer to have non-threadsafe functions in a library whose primary use is in a heavily concurrent environment.

**Comment by apechimp** [comment]
> The Flush method essentially calls Stop then Start, and it's the time between stopped and restarted state that's the issue, right?

Yup!

> What would you think of exploring the idea of saving off a copy of the existing transmission then inverting the order? Instead of Stop then Start, make it Start then Stop?

This is basically in-line with my thinking, but moving the responsibility of thread safety from the transmission to the client (and being clearer and far less hand-wavey 😁). 

> I don't know if this is feasible - it's been too long since I dug deeply in this code. I think it might involve adding a new function to the Sender interface: Copy which would return a (started or not) copy of the transmission implementation. I don't know how I feel about adding to the Sender interface - if it were possible to perform the "copy" by creating a new one based on the configs that the Client still has, that would be even better.

It looks like the `transmission.Sender` is actually passed into the client, so the client has no way of creating one unless we added `Copy` to the interface or changed the client to accept a transmission factory of some kind. 

I strongly agree re: 2 being dodgy. It does have one advantage over the other approaches though: no interfaces would need to change. 

Here's my current understanding of the options.

1. Add a `Flush` method to the `transmission.Sender` interface, and call it from `Client.Flush`. Implement it in the default implementation through the following sequence.
   - acquire a lock
   - create a new `muster.Client` and `Start` it.
   - replace the existing `muster` with ☝️ 
   - release the lock
   - call `Stop` on the old `muster`
2. Keep all the existing interfaces, but change the meaning of `Stop` for the default transmission to first create a temporary queue, then adapt `Add` to use the temporary queue when it exists.
3. Add a `Copy` method to the `transmission.Sender` interface and follow the approach you outlined. I think changing the top-level API to accept a transmission factory instead of a transmission will likely be quite disruptive.

I lean towards option 1. because it makes the `transmission.Sender` responsible for having `Flush` be threadsafe. It does require a change to the `transmission.Sender` interface, but it appears to only be used in the `Client`. Working around the specific concurrency issue with a `transmission.Sender` implementation inside the `Client` seems undesirable.

**Comment by maplebed** [comment]
If we're going to be changing the `Sender` interface, adding `Flush` feels like a much more sensible change than `Copy`. #1 sounds to me like the best choice. I appreciate that it gives different implementations of transmission their own method for flushing content independent of shutting everything down (eg for a file writer it could call `sync` instead of `close` then `open`). 

Given it's proposing changing an exported interface, I'd love the integrations team to weigh in. @paulosman what's your take?

**Comment by toshok** [comment]
Just wanted to voice my support x1000 for the "swap in a new implementation while a lock is held" as the way to go (and I'd go one step further and say only the swap should happen in the lock):

```
  newMuster := createMuster()
  newMuster.Start()

  lock()
  oldMuster = self.muster
  self.muster = newMuster
  unlock()

  oldMuster.Stop()
```

That said, I really wish there was a CAS operation we could use here.  that would cut down on how many new musters get created/started when there are multiple racing goroutines.

**Comment by paulosman** [comment]
I agree that option 1 above (Add a `Flush` method to the `transmission.Sender` interface) seems like the best way to go. It seems the most intuitive to me. 

Thanks for bringing this up, @apechimp! Are you still willing to work on a PR? If so, feel free to assign me as a reviewer and I'll make sure it gets looked at quickly.

**Comment by apechimp** [comment]
🆒 

I'll have some time to work on this tomorrow, so I'll aim to get a PR up then.
